### ISSUE TITLE
Lables on graph not matching section topic

### ISSUE THREAD

**Issue by rahkeemg** [learn-co-curriculum/dsc-deeper-neural-networks#1]
It seems that this graph within its respective subsection is mislabeled.
Also, if possible, could a legend be added to the plot, to identify which plot is the derivative and which is the original?

![Possible_mislabeled_graph](https://user-images.githubusercontent.com/5419419/72168593-72f7a080-339b-11ea-8665-879033430d0c.png)

**Comment by sumedh10** [comment]
Thanks, this is fixed.
