### ISSUE TITLE
Mislabled Relu Visual

### ISSUE THREAD

**Issue by FerdinandBeaman** [learn-co-curriculum/dsc-deeper-neural-networks#2]
## Link to Canvas

https://learning.flatironschool.com/courses/6224/assignments/226833?module_item_id=530222

## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [x ] Layout/rendering issue
- [ ] Instructions unclear
- [ ] Other (explain below)

### Source

```
plt.title('ReLU')
y = relu(z)
dy = relu(z, derivative=True)
plt.axhline(color='gray', linewidth=1,)
plt.axvline(color='gray', linewidth=1,)
plt.plot(z, dy, 'b', label='original (y)')
plt.plot(z, y, 'r', label='derivative (dy)')
plt.legend();
```

### Concern

The labels above should be switched. The derivative is being labeled as the line, and vice versa.

## What OS Are You Using?

- [ ] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [ ] Saturn Cloud from Canvas

**Comment by bpurdy-ds** [comment]
Thank you for bringing this to our attention. We'll take a look.

**Comment by bpurdy-ds** [comment]
Oops. You are correct.

**Comment by bpurdy-ds** [comment]
Fixed.
