### ISSUE TITLE
color mismatch on relu plot

### ISSUE THREAD

**Issue by joeldmott** [learn-co-curriculum/dsc-deeper-neural-networks#3]
## Link to Canvas

https://learning.flatironschool.com/courses/6537/pages/deeper-neural-networks?module_item_id=609933

## Issue Subtype

- [x] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [x] Layout/rendering issue
- [ ] Instructions unclear
- [ ] Other (explain below)

### Source

```
plt.plot(z, dy, 'b', label='original (y)')
plt.plot(z, y, 'r', label='derivative (dy)')
```

### Concern

The second half of this lesson shows plots for different activation functions along with their derivatives. Up until code cell 5 (which shows the relu activation function), the original function line is red and the derivatives are shown as a blue line. However, in this cell, the colors are switched and this can be a little confusing at first. 

## (Optional) Proposed Solution

Just switching the colors to match how the previous graphs did it. 

## What OS Are You Using?

- [ ] OS X
- [x] Windows
- [ ] WSL
- [ ] Linux
- [ ] Saturn Cloud from Canvas

**Comment by bpurdy-ds** [comment]
Thanks for flagging this. This was an issue, but it has been fixed. See https://github.com/learn-co-curriculum/dsc-deeper-neural-networks
If you are reaching this confusing code via Saturn Cloud, then you need to resource that. Your instructor can tell you how to do that, if you have not been taught already.
I'll close the ticket, but if I'm missing something, please reopen.
Thanks.
